In [1]:
a = [3.6, 2, 4]


In [2]:
import numpy as np

norm_a = np.linalg.norm(a)

In [5]:
a1 = a/norm_a

In [9]:
V = np.matmul(a1,np.transpose(a1))
V

np.float64(1.0)

In [18]:
a1 = np.array(a1)
a1 = a1.reshape(-1, 1)

In [20]:
a1t = a1 @ a1.T
a1t = 2* a1t

In [34]:
a1t

array([[0.78640777, 0.4368932 , 0.87378641],
       [0.4368932 , 0.24271845, 0.48543689],
       [0.87378641, 0.48543689, 0.97087379]])

In [33]:
HX1 = np.eye(3) - a1t
HX1

array([[ 0.21359223, -0.4368932 , -0.87378641],
       [-0.4368932 ,  0.75728155, -0.48543689],
       [-0.87378641, -0.48543689,  0.02912621]])

In [36]:
HX1@A0

matrix([[-4.15533981, -5.46601942],
        [-0.86407767, -0.59223301],
        [-1.72815534, -2.18446602]])

In [32]:
b1 = np.array([3, 5])
norm_b1 = np.linalg.norm(b1)
b1 = b1/norm_b1
b1

array([0.51449576, 0.85749293])

In [26]:
A0 = np.matrix([[1, 1], [2, 3], [4, 5]])
A0

matrix([[1, 1],
        [2, 3],
        [4, 5]])

In [27]:
Q, R = np.linalg.qr(A0)

In [28]:
Q

matrix([[-0.21821789,  0.53452248],
        [-0.43643578, -0.80178373],
        [-0.87287156,  0.26726124]])

In [29]:
R

matrix([[-4.58257569, -5.89188304],
        [ 0.        , -0.53452248]])